### ISSUE TITLE
Results from search form does not show public modules

### ISSUE THREAD

**Issue by mathieuboniface** [unibet/puppet-forge-server#10]
By searching a module on the Web-ui, I do not see any public modules.

For example, `http://puppetforge.fr.corp.acme.com/modules?query=apache` does not show any results.

However, the private modules (owned by puppet-forge-server) are visible when submitting valid search keyword.

![screen shot 2015-04-27 at 17 13 24](https://cloud.githubusercontent.com/assets/739192/7350654/c3b23de6-ed00-11e4-954f-6afe95f339fc.png)

**Comment by i11** [comment]
Thanks for letting me know. Web UI was kind of a quick hack. I'll take a look in the evening.

**Comment by i11** [comment]
Fixed in 1.5.1
