### ISSUE TITLE
A puppet module to install puppet-forge-server

### ISSUE THREAD

**Issue by mathieuboniface** [unibet/puppet-forge-server#12]
It would be nice as a puppet administrator to install a private forge using a puppet module.

Some notes : 
- Puppet support gem package provider
- This module could support various OS variants easily
- This module could support the installation behind an enterprise proxy

**Comment by i11** [comment]
There is one. Please checkout https://github.com/unibet/puppet-forge_server

**Comment by mathieuboniface** [comment]
Woow so nice ! Thanks for the link.
