### ISSUE TITLE
A new route to submit private modules

### ISSUE THREAD

**Issue by mathieuboniface** [unibet/puppet-forge-server#14]
I haven't found any way in order to publish private modules to the forge.

It would be nice to have an endpoint to push new releases of private modules.

This could be done through an http POST using Basic Authentication ?

**Comment by i11** [comment]
/v2/releases end point is used for that. It provides the official way of publishing the modules.
Authentication supposed to be implemented using OAuth, but current oauth end point are bogus and basically doesn't ensure any authentication what so ever. However it could be protected by terminating HTTP calls using nginx, apache or something else of that sort.

Ideally proper oauth request handling should be implemented.

I can recommend looking into https://github.com/maestrodev/puppet-blacksmith for automating the module deployment.

**Comment by i11** [comment]
Please let me know if there are any doubts or concerns about the module submission process or used end points, otherwise I will be closing this issue in a short while.

**Comment by mathieuboniface** [comment]
Ok, I understand. Thanks for the link about puppet-blacksmith. As we have to go fast... I wrote a cgi script to upload our modules, it's clearly a temporary solution. However according with you, it would be nice to have a better solution out of the box.
