### ISSUE TITLE
This project violates the license of Puppet Library

### ISSUE THREAD

**Issue by drrb** [unibet/puppet-forge-server#21]
This project is based on [Puppet Library](https://github.com/drrb/puppet-library) (it includes source code from Puppet Library, and credits Puppet Library in the readme file). I own the copyright to Puppet Library, and have licensed it under the [GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html).

From the GPL:

> #### 5. Conveying Modified Source Versions.
>
>You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:

>    a) The work must carry prominent notices stating that you modified it, and giving a relevant date.
>    b) The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to “keep intact all notices”.
>    c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.
>    d) If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.
>
> A compilation of a covered work with other separate and independent works, which are not by their nature extensions of the covered work, and which are not combined with it such as to form a larger program, in or on a volume of a storage or distribution medium, is called an “aggregate” if the compilation and its resulting copyright are not used to limit the access or legal rights of the compilation's users beyond what the individual works permit. Inclusion of a covered work in an aggregate does not cause this License to apply to the other parts of the aggregate.

This project is currently in violation of the GPL, because a condition of modifying and conveying Puppet Library's code is that the modified code must only be made available under the GPL. This project currently claims to be licensed under the Apache 2 license. Please remove the references to the Apache 2 license, and apply the GPL to this project.

**Comment by i11** [comment]
Thanks for point it out. The code fractions used from puppet-library are really small and mostly are left there to give you credit. But if you insist I will remove any code and references that came with puppet-library. I will have it fixed with 48h. Hope that's fast enough.

**Comment by i11** [comment]
Code and references removed. The issue will be closed after releasing it.

**Comment by i11** [comment]
1.7.0 released addressing this issue. Considering it being fixed.
