### ISSUE TITLE
Support for queries

### ISSUE THREAD

**Issue by moix** [unibet/puppet-forge-server#3]
Hi, first of all congrats for the project, I really think is a requirement for some companies to have an internal repository where to keep puppet modules.

I have installed it and it is running fine, modules are served and external repositories such as forge.puppetlabs configured with proxy setting are served properly.

What I miss is a web ui to browse all the modules, similar to the one in puppet-library, or, at least, that search option of puppet module works; right now I see the end-point of modules?query is not implemented:

[rnduser@puppet-master forge]# puppet module search --module_repository http://192.168.1.015:9090 puppetlabs-ntp
Notice: Searching http://192.168.1.015:9090 ...
Error: Request to Puppet Forge failed.
  The server being queried was http://192.168.1.015:9090/v3/modules?query=puppetlabs-ntp&module_groups=base+pe_only
  The HTTP response we received was '404 Not Found'
Error: Try 'puppet help module search' for usage

Are there plans to implement those? search option and an ui interfaz?

Thanks and Regards.

**Comment by i11** [comment]
Hey!

Thanks a lot! Good to know we are not the only ones.

I'm not a UI guy really, but some simple interface could be brought up for sure. Could be a separate front-end project even. I will take a look at it as soon as I have some spare time.

puppet module search on the other hand I consider as core functionality and it should definitely be implemented. I think I will able to deliver it rather soon. Thanks for the heads up!

Cheers!

**Comment by i11** [comment]
I've created a separate issue for the web ui https://github.com/unibet/puppet-forge-server/issues/4

**Comment by i11** [comment]
Released 1.3.0. 

```
$ puppet module search stdlib --module_repository http://127.0.0.1:8080 --debug 
Notice: Searching http://127.0.0.1:8080 ...
Debug: HTTP GET http://127.0.0.1:8080/v3/modules?query=stdlib
NAME                              DESCRIPTION                                                                  AUTHOR           KEYWORDS                             
puppetlabs-stdlib                 Standard library of resources for Puppet modules.                            @puppetlabs      library stdlib standard stages       
hardening-hardening_stdlib        Shared functions for hardening modules                                       @hardening       stdlib hardening                     
netdevops-netdev_stdlib           Type definitions for Networking Device (netdev) Library                      @netdevops       networking netdevops                 
juniper-netdev_stdlib_junos       Junos Provider code for Networking Device (netdev stdlib) Library            @juniper         networking juniper netdevops junos   
mellanox-netdev_ospf_stdlib       Type definitions for Networking Device (netdev) OSPF Library                 @mellanox        netdev ospf l3 area router route     
mellanox-netdev_stdlib_mlnxos     Provider definition for implementing Networking Device (netdev) Library ...  @mellanox        mlnxos switch l2 l3 vlan lag lacp    
aristanetworks-netdev_stdlib_eos  NetDev Providers for Arista EOS                                              @aristanetworks  network eos netdev arista            
trlinkin-validate_multi           Validate that the first argument given can pass validation of at least o...  @trlinkin        parser dsl validate stdlib           
puppetlabs-java                   Installs the correct Java package on various platforms.                      @puppetlabs      java stdlib runtime jdk jre          
brainsware-resources_deep_merge   provides a function deep-merges every memeber of one hash1 with hash2        @brainsware      deep-merge stdlib function           
ptomulik-ptlib                    Utility functions for puppet module developers                               @ptomulik        stdlib custom delete undefs param    
puppetlabs-activemq               Installs and configures ActiveMQ.                                            @puppetlabs      java activemq amqp stomp stdlib      
leonardothibes-util               My Standard Library for Puppet Modules                                       @leonardothibes  util stdlib library                  
```

**Comment by moix** [comment]
amazing! that's a record implementation time!

I'm checking it right now, thanks!

**Comment by i11** [comment]
Closing https://github.com/unibet/puppet-forge-server/issues/4 issue. 1.4.0 has been released containing built-in web ui.

if you don't like the built-in one, checkout ```puppet-forge-server  --help``` in particular *--webui-root* flag
