### ISSUE TITLE
Provide a simple web UI

### ISSUE THREAD

**Issue by i11** [unibet/puppet-forge-server#4]
Could be standalone front-end project as well

**Comment by i11** [comment]
Draft version. Any feedback is more than welcome.
https://github.com/unibet/puppet-forge-server/tree/draft1.4.0

**Comment by i11** [comment]
Released 1.4.0

**Comment by moix** [comment]
Hi Ilja,

sorry couldnt try it till today, I upgraded the gem to 1.4.0 and give it a go.

It works really nice! :)

Thanks a lot for your contribution, we'll keep in touch ;)

**Comment by i11** [comment]
Sure thing. Thanks for the heads up and let me know if you would face any issues.
