### ISSUE TITLE
http_proxy authentication not working.

### ISSUE THREAD

**Issue by senax** [unibet/puppet-forge-server#47]
Hi,

At work we have to authenticate to our web proxy. Setting ENV['http_proxy'] does not work for this as OpenURI does not support the http://username:password@proxy:port/ syntax.

I've got a patch to make this work and will submit a pull request shortly.

Thanks,
Frank

**Comment by i11** [comment]
Feel free to close it, since you've fixed it yourself with https://github.com/unibet/puppet-forge-server/pull/48. Thank you once again!

**Comment by senax** [comment]
Thanks
