### ISSUE TITLE
Only ever binds to 0.0.0.0 regardless of CLI settings

### ISSUE THREAD

**Issue by GhostLyrics** [unibet/puppet-forge-server#59]
I tried getting puppet-forge-server to bind to another IP, without any luck.

I tried:
- `--bind-host 127.0.0.1` (as I found old references to that)
- `--bind 127.0.0.1`
- `-b 127.0.0.1`
- `-b 172.17.0.1` (for Docker)
- this was on Ubuntu 14.04 but for good measure I spun up a CentOS 7.3 instance which had the same issue.

I could not find the issue since the calls in `option_parser.rb` seem to be exactly the same ones as just above for `port`. Those work.

**Comment by GhostLyrics** [comment]
You can also see the bindings not being appliyed in the logs provided in #57.

**Comment by i11** [comment]
Thanks to @dpattmann for fixing it!
