### ISSUE TITLE
I'm trying to add the puppet-forge-server created forge to pulp-foreman, but seems that pulp can't find the repo. ¿Which is the correct path?

### ISSUE THREAD

**Issue by volapuk** [unibet/puppet-forge-server#6]

**Comment by i11** [comment]
Hi! Could you please provide a bit more details on what exactly you're trying to do. A sequence of commands and outputs would help to understand your use case if that's possible.

Depending on the arguments used for starting the server the URL might differ, but the default one would be http://<machine hostname>:8080/ (e.g. http://localhost:8080). URL could be used as feed for pulp repository.

**Comment by i11** [comment]
Please let me know if you still have any issues, otherwise I'll be closing it tomorrow.
