### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hickey** [unibet/puppet-forge-server#69]
Any chance we can get a new release of puppet-forge-server? Preferably after PRs for #68 and #67 have been processed. And of corse any others that are ready, but it looks like those are the only two really ready to go. 

After the new release I would be happy to build a new Docker container of the release. I think there are a couple of other useful updates that have occurred since 1.9.0 and hence why I am suggesting we get another release out there...... Please......

https://hub.docker.com/r/hickey/puppet_forge/

FWIW, I have a Helm Chart that will be available shortly for running inside Kubernetes. Maybe we should add pointers to the Docker container and the Chart in the README file for this release. Let me know and I will finish the Chart in the next couple of days for the release.

**Comment by i11** [comment]
Release done.
It would be great to have it in the README. Thanks!

**Comment by i11** [comment]
Closing. Feel free to re-open for whatever reasons
